### ISSUE TITLE
tvOS app Focuse update

### ISSUE THREAD

**Issue by Rohit737-star** [THEOplayer/samples-ios-sdk#11]
Hello team,

i am developing tvOS app , i have added two button suppose B1 and B2  in super view of  player i want to update Focus between this two button B1 and B2 but when initialise code that  time i am able to get focus in B1 but when clicking system left and right arrow key or top and down arrow key in (testing in simulator) that time focus always jumping in player seek bar (but its should be jump in B2 button) after jumping on seek bar never to came back on button B1,b2. so please provide me if any override method if available in sdk or send me any reference. thanks

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

If you are trying to go "back" to change the focus on tvOS, you need to use `override func pressesBegan`. An example:

```
override func pressesBegan(_ presses: Set<UIPress>, with event: UIPressesEvent?) {
    super.pressesBegan(presses, with: event)
    guard let buttonPress = presses.first?.type else { return }
    if buttonPress == .menu {
        self.menuButtonPressed()
    } else if (buttonPress == .playPause) {
        self.playPause()
    }
}

@objc private func playPause() {
    if player.paused {
        player.play()
    } else {
        player.pause()
    }
}

@objc private func menuButtonPressed() {
    self.navigationController?.popViewController(animated: true)
}
```

The `playPause` function here is to toggle playback even when the viewer isn’t highlighting the player. Please let us know if this helps you solve the issue you are seeing.

Kind regards

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,
Since we have not heard from you for a while, we are assuming that you could solve your issue with the solution we provided and close this issue.

Feel free to open another one if you are still having problems.

Kind regards
