### ISSUE TITLE
Hide Full screen option from player

### ISSUE THREAD

**Issue by Rohit737-star** [THEOplayer/samples-ios-sdk#15]
Hello team,

How we can hide full screen option from player in iOS app. please suggest me sir. thanks

**Comment by Rohit737-star** [comment]
hello team,

please reply sir it is possible or not in your sdk. i am waiting.

**Comment by sree963** [comment]
Hi @Rohit737-star ,

Yes, it is possible to hide full screen option. It can be achieved by modifying CSS style.
Please use below line of code to hide full screen option on the player.

```
.vjs-icon-fullscreen-enter, .video-js .vjs-fullscreen-control {
display: none; 
}
```

Hope below document would be helpful while dealing with UI elements.
https://docs.theoplayer.com/how-to-guides/11-ui/09-customize-ui-during-playback.md

Thanks

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

Since we have not heard from you for a while, we are assuming that you could solve your issue with the solution we provided and close this issue.

Feel free to open another one if you are still having problems.

Kind regards
