### ISSUE TITLE
Getting Error in live build "THE GIVEN LICENCE IS INVALIDE"

### ISSUE THREAD

**Issue by Rohit737-star** [THEOplayer/samples-ios-sdk#21]
Hello Team,

i was uploaded new build on app store used Licence Key and Licence URL both but after two month showing message in live build "THE GIVEN LICENCE IS INVALIDE"  . can u explain guys how i can make licence key permanent , i think i need to upload new build again on app store here is my used code for Licence configuration please check.

THEOplayerConfiguration(chromeless: false, defaultCSS: true, cssPaths: [stylePath1], jsPaths: [], jsPathsPre: [], analytics: [], pip: nil, ads: nil, ui: nil, cast: nil, hlsDateRange: nil, license: Licences.LICENCE_iPhone_SDK, licenseUrl: Licences.LICENCE_URL_iPhone, verizonMedia: nil)

please help

**Comment by thijsl** [comment]
Hi @Rohit737-star ,

In your iOS app, you should only configure `license` OR `licenseUrl`. I wouldn't recommend configuring both.
Most likely, either the value for `license` or for `licenseUrl` contains an expired license. 

To resolve this, remove `licenseUrl`, login to https://portal.theoplayer.com/, take the license value, and replace it in your iOS app. To avoid similar issues in the future, you could implement some sort of mechanism that locally "caches" the license value by requesting it everyone once in a while from a HTTPS service you maintain.

Hope that makes sense! :-) 

Kind regards,
Thijs

**Comment by Rohit737-star** [comment]
hello sir,

some day ago i was uploaded build with only with LICENCE KEY that time same issue was occur after that i was used LICENCE and LICENCE_URL both my question is that how i can update licence without upload new build on app store sir.
