### ISSUE TITLE
Player is not renderering video - black screen

### ISSUE THREAD

**Issue by DevakiNandanSharma1995** [THEOplayer/samples-ios-sdk#22]
I am not getting video in iPhone X, iPhone 11 and above models.

But audio is working.

Please help me

**Comment by thijsl** [comment]
Hi @DevakiNandanSharma1995 ,

Can you re-raise this issue through https://servicedesk.theoplayer.com/?

Furthermore, in that ticket, can you answer the following questions:

1/ Are you using simulators, or physical devices? 
2/ What version of XCode are you using?
3/ What version of macOS are you using?
4/ Which THEOplayer iOS SDK version are you using?
5/ Which streams are you playing?
6/ Are you using DRM protected content on simulators?

Kind regards,
Thijs

**Comment by DevakiNandanSharma1995** [comment]
Hi @thijsl 

1/ Are you using simulators, or physical devices?
Answer:- I am Using Physical devices.

2/ What version of XCode are you using?
Answer:- Xcode Version 13.0 (13A233)

3/ What version of macOS are you using?
Answer:- macOS Monterey version 12.0.1 (21A559)

4/ Which THEOplayer iOS SDK version are you using?
Answer:- Version - Current : 2.85.3

5/ Which streams are you playing?
Answer:- hls 

6/ Are you using DRM protected content on simulators?
Answer:- We are using aes 128 encrypted content in physical device.

Kind regards
Devaki Nandan

**Comment by ceyhun-o** [comment]
Hi,

Closing this issue since this is handled on Service Desk. Feel free to reach out again on our Service Desk again in case you have any other questions.

Kind regards,
Ceyhun
