### ISSUE TITLE
Accessory View

### ISSUE THREAD

**Issue by pcentieiro** [THEOplayer/samples-ios-sdk#6]
Hello,

I'm having an odd behaviour: when I click on the bottom of the player, the accessory view (in my case it's a input text field, since we've a stream above a chat view) gets hidden.

You can replicate it by adding an accessory view, and then click on the on the area of the controls bar. I made a video using a demo project, in this case the red area on the bottom is the accessory view: https://www.dropbox.com/s/i2n9tiwyv87v2kx/Screen%20Recording%202020-08-27%20at%2023.31.42.mov?dl=0

**Comment by savdeepgandhi13** [comment]
Please reach out to team for the support on your apps.
