### ISSUE TITLE
building for tvOS Simulator, but linking in dylib built for iOS Simulator

### ISSUE THREAD

**Issue by Rohit737-star** [THEOplayer/samples-ios-sdk#7]
Hello team,

i am developing app for iOS and tvOS but when adding **THEOplayer SDK for tvOS target** its produced error-
**"building for tvOS Simulator, but linking in dylib built for iOS Simulator, file '/Users/shinewebsolutions/Documents/Rohit_Working/Dacast_Player/Dacast/DecastPlayer/THEOplayerSDK.framework/THEOplayerSDK' for architecture x86_64"**

**i unable to find solutions of this issue . please help**

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

You might need to exclude the unused architectures in your SDK to resolve this. Please see the following article: https://docs.theoplayer.com/getting-started/01-sdks/03-ios/02-app-doesnt-want-to-build-app-store.md

If the article doesn't help, can you please provide the following information?

- When do you get this error? While building or uploading your app?
- Which version of THEOplayer SDK are you using and where did you get it?
- Which version of XCode do you build with?

**Comment by Rohit737-star** [comment]
> Hi @Rohit737-star,
> 
> You might need to exclude the unused architectures in your SDK to resolve this. Please see the following article: https://docs.theoplayer.com/getting-started/01-sdks/03-ios/02-app-doesnt-want-to-build-app-store.md
> 
> If the article doesn't help, can you please provide the following information?
> 
> * When do you get this error? While building or uploading your app?
> * Which version of THEOplayer SDK are you using and where did you get it?
> * Which version of XCode do you build with?

-------------------------***************************************------------------------------
sir i have added this script in RUN SCRIPT in xcode but nothing happened i have follow your docs-

**APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"
# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"
done**

if you need more information i have mention below please check-

**1- When do you get this error? While building or uploading your app?**
**answer**- **Getting this Error compile time(building).**

**2-Which version of THEOplayer SDK are you using and where did you get it?**
Answer-  **2.68.1**

**3- Which version of XCode do you build with?**
Answer- **xCode Version 12.2 (12B45b)**

please check and help sir since 6 days i have stuck on this issue.

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

This is hard to pinpoint for us as we cannot reproduce this on our side. We have a few steps to recommend while building with XCode 12 though:

First of all try to exclude the architectures this way:

1) Open the workspace in Xcode 12.
2) On the left panel, click on the Project Navigator (the folder icon).
3) Select the project.
4) Switch to the Build Settings tab.
5) Expand the Excluded Architectures entry by clicking on the arrow icon next to it.
6) Hover over the Release setting. A + icon will appear, click it.
7) By default, the setting will be set to apply to Any SDK, click it to edit.
8) From the dropdown menu select Any iOS Simulator.
9) Double click on the empty field on the right side to add a new value.
10) Click on the + icon at the bottom of the pop-up.
11) Enter arm64 as the value and press return.

Secondly, go to Build Settings for your project and set Validate Workspace to yes.

If these don't work, can you try to build with the latest version of our SDK and check if you are seeing the message there too?

Kind regards,
Ceyhun

**Comment by Rohit737-star** [comment]
Hello sir,

i have follow your answer but nothing happen still getting same error.

**Here i have added more details about issue and my project i think it will be helpful to you in reproduce error-** 

**1- i am using THEOplayer 2.68.1 version sdk and xcode 12.2.** 

**2- i am developing iOS and tvOS app in single project by adding multiple target (for - iOS and tvOS).**

**3- iOS target app working fine without any issue.**

**4- tvOS target app has issue during compile time xCode produce error message** **(building for tvOS Simulator, but linking in dylib built for iOS Simulator, file '/Users/shinewebsolutions/Documents/Rohit_Working/Dacast_Player/Dacast/DecastPlayer/THEOplayerSDK.framework/THEOplayerSDK' for architecture x86_64)**

**5- if you are unable to reproduce error please follow below step-** 

**- Use xcode 12 or latest and make demo for iOS and tvOS in single project by adding multiple target (for - iOS and tvOS).**
**- Run tvOS target app i am sure you will get this error. if you will not get any error please update me i am waiting.**

Thanks and regard
Rohit Nishad

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

Please update your THEOplayer SDK to the latest version (2.81.1) and let us know if you still see this issue. I cannot reproduce this on my side on a project with both iOS and tvOS as targets.

To update your SDK, login on THEOportal, create a new SDK and replace your framework with the new one.

If you are still experiencing the issue on the latest version, we might need to ask for a minimal reproduction app from you to see what the issue is. As we think this should not be shared publicly, kindly create a Service Desk ticket so we can further investigate.

Kind regards

**Comment by Rohit737-star** [comment]
Thanks for support sir
