### ISSUE TITLE
ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks

### ISSUE THREAD

**Issue by Rohit737-star** [THEOplayer/samples-ios-sdk#8]
Hello team,

**I am trying to upload app on app store test flight but getting rejection from apple side due to THEOplayer framework. please check i have mention whole message below.-**

Dear Developer,

We identified one or more issues with a recent delivery for your app, "Endless Earth" 1.0 (1.0). Please correct the following issues, then upload again.

**ITMS-90338: Non-public API usage - The app references non-public selectors in** Frameworks/THEOplayerSDK.framework/THEOplayerSDK: addChannel:, addListener:, connectionState, contentID, customData, friendlyName, initWithURL:width:height:, playerState, removeListener:, requestID, requestStatus, setDate:forKey:, streamPosition. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

--

**Please check this issue and give me solutions.**

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

What is the THEOplayer SDK version you are trying to upload? And is your app targeting iOS or tvOS?

We fixed a similar issue on 2.68.1 and I assume you are using this version (as you shared on your other ticket). Can you also try the latest version of the SDK and let us know if you are still getting the same message?

**Comment by Rohit737-star** [comment]
hello sir,

thanks for answer -

first i want to tell you i am using latest sdk (2.68.1 version). please check sir. apple direct producing issue of sdk.

1- i am using 2.68.1 version sdk. 
2- i have try to upload app for iOS.

thanks

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

As I mentioned on my previous comment, there was an issue on 2.68.1 that we fixed on 2.69.0. The latest version of our SDK is at this moment 2.81.1. Please login to THEOportal to get a newer version of your SDK or contact your CSM.

Kind regards

**Comment by Rohit737-star** [comment]
hello team,

please can you provide me tvOS demo link or .zip file my mail - rohitn.shineweb@gmail.com

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

We are working on creating a tvOS samples repository soon. Unfortunately we do not have a sample we can publicly share at the moment. 

Regarding this ticket itself, if you do not have your credentials to login on THEOportal or if you need a tvOS sample app, contact your CSM or where you acquired the framework for possible solutions.

Kind regards

**Comment by Rohit737-star** [comment]
Hello sir,

I am working on tvOS app , i have follow to docs , but player screen always showing blank,  showing only seek bar. here is simple code-

```
        
   class TV_PlayerVC: UIViewController {

    @IBOutlet weak var plView:UIView!

    override func viewDidLoad() {
        super.viewDidLoad()

        
        THEOplayer.prepare(withFirstViewController: UIStoryboard(name: "Main", bundle: nil).instantiateInitialViewController()!)
        let theoplayer = THEOplayer(with: CGRect(x: 0, y: 0, width: self.plView.frame.width, height: self.plView.frame.height))
        
        theoplayer.addAsSubview(of: self.plView)
        
        let source = SourceDescription(sources: [TypedSource(src: "https://dacasts3-vh.akamaihd.net/i/secure/181896/181896_,1025764.raw,.csmil/master.m3u8", type: "application/x-mpegurl")])
        theoplayer.source = source
        theoplayer.play()
    }

}

```

please let me know sir where i am doing wrong. thanks

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

As we have answered your initial question with this issue, I am closing it now. Feel free to open a new one if you have further questions.

Kind regards
