### ISSUE TITLE
tvOS app Player screen issue

### ISSUE THREAD

**Issue by Rohit737-star** [THEOplayer/samples-ios-sdk#9]
Hello sir,

I am working on tvOS app , i have follow to docs , but player screen always showing blank, showing only seek bar. here is simple code-

```
class TV_PlayerVC: UIViewController {

    @IBOutlet weak var plView:UIView!

    override func viewDidLoad() {
        super.viewDidLoad()

        
        THEOplayer.prepare(withFirstViewController: UIStoryboard(name: "Main", bundle: nil).instantiateInitialViewController()!)
        let theoplayer = THEOplayer(with: CGRect(x: 0, y: 0, width: self.plView.frame.width, height: self.plView.frame.height))
        
        theoplayer.addAsSubview(of: self.plView)
        
        let source = SourceDescription(sources: [TypedSource(src: "https://dacasts3-vh.akamaihd.net/i/secure/181896/181896_,1025764.raw,.csmil/master.m3u8", type: "application/x-mpegurl")])
        theoplayer.source = source
        theoplayer.play()
    }

}
```

please let me know sir where i am doing wrong. thanks

**Comment by ceyhun-o** [comment]
Hi @Rohit737-star,

We have published our first public tvOS sample today. You can clone it here: https://github.com/THEOplayer/samples-tvos-sdk

Please let us know if this is helpful for getting your app running.

Kind regards

**Comment by Rohit737-star** [comment]
Thanks for helping sir. finally i have fixed . my suggestion if you updating SDK you also need to update docs same time. tvOS code are different from you demo code.  and docs code does not working always show blank screen. your demo is working perfect.
